server:
  port: 8081
spring:
  application:
    name: Customer-Service
    
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: password
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: smith
  jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
      

management:
   endpoints:
     web:
      exposure:
        include: '*'
        
api_doc_url: null 
