eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8084

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/,/login/**,/logout/**,/swagger**,/ai/**,/customer/**

          filters:
           - AuthenticationFilter


        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/**

          filters:
           - AuthenticationFilter

        
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**

          filters:
           - AuthenticationFilter
           

        - id: ORDERED-SERVICE
          uri: lb://ORDERED-SERVICE
          predicates:
            - Path=/ordered/**

          filters:
           - AuthenticationFilter
           
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
           - Path=/auth/**,/home/**
  main:
    allow-bean-definition-overriding: true
       